from .views import *
from django.urls import path
from .inventory_views import *

urlpatterns = [
    path('', owner, name='owner'),
    path('staff/', staff, name='staff'),
    path('staff/addstaff', add_staff, name='add_staff'),
    path('staff/editstaff', edit_staff, name='edit_staff'),
    path('staff/deletestaff', delete_staff, name='delete_staff'),
    path('submit-order/', submit_order, name='submit_order'),
    path('complete_order/', complete_order, name='complete_order'),
    path('delete_order/', delete_order, name='delete_order'),
    path('update_quantity/', update_quantity, name='update_quantity'),
    path('ajax/get_orders/', ajax_get_orders, name='ajax_get_orders'),
    path('order/set_started/', set_order_started, name='set_order_started'),
    path('settings', button, name='button'),
    path('settings/reports', reports, name='reports'),
    path('settings/reports/sales', sales, name='sales'),
    path('settings/reports/sales/dailytransc', dailytransc, name='dailytransc'),
    path('settings/reports/sales/monthlytransac', monthly_report, name='monthlytransac'),
    path('settings/reports/sales/custom_period', custom_period, name='custom_period'),
    path('settings/reports/revenue', revenue, name='revenue'),
    path('settings/reports/inventory', inventory, name='inventory'),
    path('settings/reports/inventory/add', add_inventory_item, name='add_inventory_item'),
    path('settings/reports/inventory/edit', edit_inventory_item, name='edit_inventory_item'),
    path('settings/reports/inventory/delete/<int:item_id>/', delete_inventory_item, name='delete_inventory_item'),
    path('settings/reports/inventory/transaction', inventory_transaction, name='inventory_transaction'),
    path('settings/reports/inventory/history', inventory_history, name='inventory_history'),
    path('settings/reports/timeanalysis', timeanalysis, name='timeanalysis'),
    path('settings/categories/', category, name='category'),
    path('settings/categories/add/', add_category, name='add_category'),
    path('settings/categories/edit/', edit_category, name='edit_category'),
    path('settings/categories/delete/<int:category_id>/', delete_category, name='delete_category'),
    path('settings/items/', item, name='item'),
    path('settings/items/add/', add_menu_item, name='add_menu_item'),
    path('settings/items/edit/', edit_menu_item, name='edit_menu_item'),
    path('settings/items/delete/<int:item_id>/', delete_menu_item, name='delete_menu_item'),
    path('settings/table/', table, name='table'),
    path('settings/table/add/', add_table, name='add_table'),
    path('settings/table/edit/', edit_table, name='edit_table'),
    path('settings/table/delete/<int:table_id>/', delete_table, name='delete_table'),
    path('settings/billing/', owner_billing, name='owner_billing'),
    path('payment/', payment, name='payment'),
    path('getlink/<int:plan_id>', get_payment, name='get_pay_link'),
    path('cashfree_webhook', cashfree_webhook, name="cashfree_webhook"),
    path('billhistory', bill_history, name='billhistory')
]   