# Generated by Django 5.0.4 on 2025-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
