# Generated by Django 5.0.4 on 2025-03-10 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staffof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hotel'),
        ),
    ]
