# Generated by Django 5.2.6 on 2025-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplans',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
